<a href="https://colab.research.google.com/github/Jenn-mawia/mlbookcamp/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Creating arrays

## One-dimensional arrays

In [2]:
np.zeros(5) #creates array of size 5 filled with 0's

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5) #creates array of size 10 filled with 2.5's

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,4,5,7,10]) #create an array from a list of numbers
a

array([ 1,  2,  3,  4,  5,  7, 10])

In [6]:
# access element 3 from the array "a"
a[2]

3

In [10]:
# create a range from 0-10(10 is not included)
print(np.arange(10))
np.arange(3,10)

[0 1 2 3 4 5 6 7 8 9]


array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays

In [18]:
np.zeros((5, 2)) #2 dimensional array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,6,5],
    [7,8,9]
])

In [22]:
# access array elements (2)
print(n[0,1])
# change it to 20
n[0,1]=20
n

2


array([[ 1, 20,  3],
       [ 4,  6,  5],
       [ 7,  8,  9]])

In [23]:
# access entire row
n[2]

array([7, 8, 9])

In [26]:
# get entire second column
print(n[:,1])
# assign different values
n[:, 1]=[0,0,0]
n

[20  6  8]


array([[1, 0, 3],
       [4, 0, 5],
       [7, 0, 9]])

# Randomly generated arrays

In [29]:
np.random.seed(10) #makes the randomly generated arrays the same every time it is executed
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [30]:
np.random.randn(5, 2) #draw numbers from the standard normal distribution

array([[ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737],
       [-0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761]])

In [31]:
np.random.randint(low=0, high=100, size=(5,2)) #generate random integers

array([[13, 25],
       [13, 92],
       [86, 30],
       [30, 89],
       [12, 65]])

# Element-wise operations

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
# addition
a+1

array([1, 2, 3, 4, 5])

In [35]:
# multiplication
a*50

array([  0,  50, 100, 150, 200])

In [36]:
# division
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [44]:
b = (10 + (a*2))**2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [45]:
# combine two arrays: addition
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [46]:
# multiplication
a*b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

# Comparison operations

In [47]:
a

array([0, 1, 2, 3, 4])

In [48]:
a >=2 #which elements of the array satisfy the condition

array([False, False,  True,  True,  True])

In [49]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [50]:
a > b

array([False, False,  True,  True,  True])

In [51]:
# which elements of a are greater than b
a[a > b]

array([2, 3, 4])

# Summarizing operations

In [57]:
print(a)
print(n)

[0 1 2 3 4]
[[1 0 3]
 [4 0 5]
 [7 0 9]]


In [53]:
a.max() 

4

In [56]:
a.sum() #sum of the array
print(n.sum())

29


In [55]:
a.mean()

2.0